### ISSUE TITLE
可以透明化嘛标题

### ISSUE THREAD

**Issue by wx9999** [lingxiaoyi/Taro-navigation-bar#10]
使导航透明

**Comment by lingxiaoyi** [comment]
你把颜色设置成透明颜色不就行了吗?rgba(0,0,0,0.4)

**Comment by wx9999** [comment]
<img width="784" alt="QQ20191015-111310@2x" src="https://user-images.githubusercontent.com/42061047/66797377-225bdd00-ef3d-11e9-9a2f-eb954379452a.png">
想要这种

**Comment by lingxiaoyi** [comment]
这种情况我去写写demo试试,你先尝试一下

**Comment by wx9999** [comment]
好的 多谢

**Comment by wx9999** [comment]
@lingxiaoyi  搞定了
<img width="231" alt="QQ20191015-113924@2x" src="https://user-images.githubusercontent.com/42061047/66798402-787e4f80-ef40-11e9-967d-7ace03bec4e6.png">
<img width="313" alt="qian" src="https://user-images.githubusercontent.com/42061047/66798458-9b106880-ef40-11e9-9d75-19db11d6f67f.png">

**Comment by lingxiaoyi** [comment]
![image](https://user-images.githubusercontent.com/18524956/66798637-3efa1400-ef41-11e9-9893-ba0e138b0e1e.png)
我 提供了一个例子9上去了
