### ISSUE TITLE
使用该组件padding-bottom: env(safe-area-inset-bottom)不生效

### ISSUE THREAD

**Issue by wkl007** [lingxiaoyi/Taro-navigation-bar#11]
使用该组件后padding-bottom: env(safe-area-inset-bottom)在iphoneX设备下不生效了，不使用是正常的。

**Comment by lingxiaoyi** [comment]
按道理这就是个样式设置,组件不太可能影响到的,我找一个iphonex试一下

**Comment by lingxiaoyi** [comment]
![微信图片_20191022200257](https://user-images.githubusercontent.com/18524956/67283818-f923e980-f506-11e9-91ef-20b71bca02b2.jpg)
我试了,没出现问题,我把 代码加到例子9了,你参考一下,我猜测你的样式有可能搞错了

**Comment by wkl007** [comment]
好，我试试

**Comment by wkl007** [comment]
发现`padding-bottom: env(safe-area-inset-bottom)`就有这种问题，`bottom: env(safe-area-inset-bottom)`这样就没有问题了。
```
  .btn {
    position: fixed;
    right: 0;
    bottom: 0;
    left: 0;
    height: 100px;
    color: #fff;
    text-align: center;
    background: orange;
    padding-bottom: env(safe-area-inset-bottom);
    // bottom: env(safe-area-inset-bottom);
  }
```
使用`padding-bottom: env(safe-area-inset-bottom);`

<img src="https://cache-1256738511.cos.ap-chengdu.myqcloud.com/images/WechatIMG63.png" style="zoom:30%;" />

使用`bottom: env(safe-area-inset-bottom);`

<img src="https://cache-1256738511.cos.ap-chengdu.myqcloud.com/images/WechatIMG62.png" style="zoom:30%;" />

**Comment by lingxiaoyi** [comment]
你没理解透彻布局,padding-bottom并不会影响absolute布局的

**Comment by wkl007** [comment]
用的是fixed布局呀

**Comment by lingxiaoyi** [comment]
都一样 只要是定位,都是从元素最边缘开始的  包括padding-bottom
