### ISSUE TITLE
taro h5编译报错

### ISSUE THREAD

**Issue by sprout-echo** [lingxiaoyi/Taro-navigation-bar#2]
```tsx
{getEnv() === 'WEAPP' && (
        <NavBar title="拼团详情" back home onHome={() => router.switchTab('/index')} />
      )}
```
在小程序编译不会报错，h5环境下 这个自定义的导航栏应该隐藏，但是 我已经加了判断，还是会执行，报错： getSystemInfo is  not a function

**Comment by lingxiaoyi** [comment]
那说明在taro中H5环境这个代码还是编译了,你先查查为什么会执行代码,是判断不对还是默认肯定会执行,我记得taro有个功能可以分开多个环境单独写JS,你写2个JS,一个weapp的一个H5的试试

**Comment by sprout-echo** [comment]
> 那说明在taro中H5环境这个代码还是编译了,你先查查为什么会执行代码,是判断不对还是默认肯定会执行,我记得taro有个功能可以分开多个环境单独写JS,你写2个JS,一个weapp的一个H5的试试

嗯啊，加了判断编译环境 process.env.TARO_ENV 就可以了

**Comment by lingxiaoyi** [comment]
已加H5兼容条件判断
