### ISSUE TITLE
某些特殊情况下 getMenuButtonBoundingClientRect 返回的 right = screenWidth

### ISSUE THREAD

**Issue by 502647092** [lingxiaoyi/Taro-navigation-bar#33]
有时候 获取 Rect 的 right = screenWidth 
应该再加一个异常情况right = screenWidth的时候用自己计算的值
当然也有可能是QQ的问题 我已经反馈到QQ那边了

**Comment by lingxiaoyi** [comment]
极少数的极端问题暂时就不考虑了，毕竟各机型差异太大，很难100%兼顾的

**Comment by 502647092** [comment]
嗯 好的
我看看有没有解决方案
