### ISSUE TITLE
下次写组件请你不要用sass谢谢

### ISSUE THREAD

**Issue by Harry-Vin** [lingxiaoyi/Taro-navigation-bar#41]
每次编译sass要费几个小时的折腾时间，有的时候装windows-build-tools都不一定能编好，头疼，还以为能现拿现用，谁知道花了几个小时编译sass

**Comment by Mayandev** [comment]
为什么会有这样的 issues...用什么样的方式编写样式是作者的自由。再者，Taro 默认支持 SASS，应该是你的使用姿势问题。

**Comment by Harry-Vin** [comment]
> 为什么会有这样的 issues...用什么样的方式编写样式是作者的自由。再者，Taro 默认支持 SASS，应该是你的使用姿势问题。

好的，我很菜，我要是稍微强点就能自己写了

**Comment by Harry-Vin** [comment]
sorry
